name: Get next release version from semantic release dry run

on:
  workflow_call:
    outputs:
      release-version:
        value: ${{ jobs.get-release-version.outputs.release-version }}

jobs:
  get-release-version:
    name: Get next release version
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.extract-release-version.outputs.release_version }}
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: extract-release-version
        run: |
          echo "$(git tag -l)"
          GH_TOKEN=${{ secrets.GITHUB_TOKEN }} npx semantic-release --dry-run --verbose > release-temp.log
          cat release-temp.log
          echo "release_version=$(cat release-temp.log | grep -oiP 'the next release version is \K.*')" >> "$GITHUB_OUTPUT"
