name: Clean up open PRs

on:
  workflow_dispatch:
    inputs:
      force_cleanup:
        description: 'Force cleanup of preview environments'
        required: false
        default: 'false'

env:
  REGION: asia-south1
  LOCATION: asia-south1-docker.pkg.dev
  PROJECT_ID: cloud-run-preview-demo
  REPO: cloud-run-repo
  IMAGE: preview-demo
  SERVICE: preview-demo
  BASE_VERSION: 1.0.0

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GAR_JSON_KEY }}

      - name: Install google cloud sdk
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '456.0.0'

      - name: Find Open PRs with Preview Label
        id: find_prs
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'preview',
            });
            console.log(pullRequests)
            # const previewPRs = pullRequests.filter(pr => pr.labels.find(label => label.name === 'preview'))
            # console.log(previewPRs)
            const devOpenPRBranches = pullRequests.filter(pr => pr.base.ref === 'main').map(pr => pr.head.ref)
            console.log(devOpenPRBranches)
