name: Clean up open PRs

on:
  workflow_dispatch:
    inputs:
      force_cleanup:
        description: 'Force cleanup of preview environments'
        required: false
        default: 'false'

env:
  REGION: asia-south1
  LOCATION: asia-south1-docker.pkg.dev
  PROJECT_ID: cloud-run-preview-demo
  REPO: cloud-run-repo
  IMAGE: preview-demo
  SERVICE: preview-demo
  BASE_VERSION: 1.0.0

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GAR_JSON_KEY }}

      - name: Install google cloud sdk
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '456.0.0'

      - name: Find Open PRs with Preview Label
        id: open-prs-branches
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            const prLastUpdatedLimit = 2 * 60 * 60 * 1000; // 2 hours
            const devOpenPRBranches = pullRequests.filter(pr => {
              const lastUpdatedAt = +(new Date(pr.updated_at));
              return pr.base.ref === 'main' && Date.now() - lastUpdatedAt > prLastUpdatedLimit;
            }).map(pr => {
              console.log(pr.head.ref)
              return pr.head.ref.split('/').slice(2)[0] || pr.head.ref;
            });
            return devOpenPRBranches;

      - name: Log branches of Open PRs more than 1 hour
        run: |
          echo ${{ steps.open-prs-branches.outputs.result }}
          echo "($(echo ${{ steps.open-prs-branches.outputs.result }} | jq -r '.[]'))"
          echo "bash_array=($(echo ${{ steps.open-prs-branches.outputs.result }} | jq -r '.[]'))" >> $GITHUB_OUTPUT

      # - name: Delete cloud run services of long opened PR branches
      #   run: |
      #     for branch in ${{ steps.open-prs-branches.outputs.result }}; do
      #       SERVICE=$(gcloud run services list --region ${{ env.REGION }} --format="value(metadata.name)" --filter="metadata.name ~ $branch")
      #       if [ ! -z $SERVICE ]; then
      #         echo "cloud run service $SERVICE for $branch found"
      #         echo "gcloud run services delete $SERVICE --region ${{ env.REGION }} --quiet"
      #       else
      #         echo "cloud run service $SERVICE for $branch not found"
      #       fi
      #     done

      # - name: Delete preview docker images of long opened PR branches
      #   run: |
      #     for branch in ${{ steps.open-prs-branches.outputs.result }}; do
      #       TAGS=$(gcloud artifacts docker tags list ${{ env.IMAGE }} --format="value(tag)" --filter="tag ~ ${{steps.open-prs-branches.outputs.result}}")
      #       echo "tags for $branch are $TAGS"
      #       for tag in $TAGS; do
      #         echo "gcloud artifacts docker images delete ${{ env.IMAGE }}:$tag"
      #       done
      #     done
