name: Clean up open PRs

on:
  workflow_dispatch:
    inputs:
      force_cleanup:
        description: 'Force cleanup of preview environments'
        required: false
        default: 'false'

env:
  REGION: asia-south1
  LOCATION: asia-south1-docker.pkg.dev
  PROJECT_ID: cloud-run-preview-demo
  REPO: cloud-run-repo
  IMAGE: preview-demo
  SERVICE: preview-demo
  BASE_VERSION: 1.0.0

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GAR_JSON_KEY }}

      - name: Install google cloud sdk
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '456.0.0'

      - name: Find Open PRs with Preview Label
        id: find-open-prs-branches
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            const prLastUpdatedLimit = 24 * 60 * 60 * 1000; // 24 hours
            const devOpenPRBranches = pullRequests.filter(pr => {
              const lastUpdatedAt = +(new Date(pr.updated_at));
              return pr.base.ref === 'main' && Date.now() - lastUpdatedAt > prLastUpdatedLimit;
            }).map(pr => pr.head.ref);
            return devOpenPRBranches;
      
      - name: Log branches of Open PRs more than 1 hour
        run: echo ${{ steps.find-open-prs-branches.outputs.result }}

