name: Clean up Cloud Run service and respective docker images post PR closure

on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  GAR_JSON_KEY: ${{ secrets.GAR_JSON_KEY }}
  IMAGE: preview-demo-pr

jobs:
  cleanup:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Parse current branch name
        id: parse-branch-name
        run: |-
          echo "${{ github.head_ref }}"
          echo "branch=$(echo ${{ github.head_ref }} | sed 's/\//-/g' | tr -d '[:space:]')" >> $GITHUB_OUTPUT

      - name: Parse cloud run service name
        id: get-cloudrun-service
        run: echo "service=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE }}/${{ env.IMAGE }}-${{ steps.parse-branch-name.outputs.branch }}" >> $GITHUB_OUTPUT

      - name: Authenticate to GCP
        id: gcp-auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GAR_JSON_KEY }}

      - name: Install gcloud sdk
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '456.0.0'

      - name: Delete cloud run service
        run: |
          echo "Delete cloud run service"
          gcloud run services delete ${{ steps.get-cloudrun-service.outputs.service }} --region ${{ env.GAR_LOCATION }}
          
      - name: Delete PR preview tags
        run: |
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev
          gcloud  artifacts docker images list ${{ steps.get-cloudrun-service.outputs.service }} --include-tags --format="flattened(package, tags[0])
          echo "Deleting preview image from GAR"
          gcloud artifacts docker images delete ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE }}/${{ env.IMAGE }}-${{ steps.parse-branch-name.outputs.branch }}
