name: Pull Request - Build when a pull request is raised against main branch

on:
  pull_request:
    branches:
      - main
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check labels
        run: echo ${{ toJson(github) }}

      - name: Run only on preview label
        if: ${{ github.event.label.name == 'preview' }}
        run: |
          echo "Running preview label step"
          echo ${{ toJson(github.event) }}

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Build the application
        run: yarn build
