name: Preview - Build and Deploy PR Preview to Cloud Run

on:
  workflow_dispatch

env:
  REGION: ${{ secrets.GAR_REGION }}
  LOCATION: ${{ secrets.GAR_LOCATION }}
  PROJECT_ID: ${{ secrets.GAR_PROJECT_ID }}
  REPO: ${{ secrets.GAR_REPO }}
  GAR_CREDENTIALS_JSON: ${{ secrets.GAR_JSON_KEY }}
  IMAGE: ${{ secrets.GAR_IMAGE }}
  SERVICE: ${{ secrets.CLOUDRUN_SERVICE }}

jobs:
  build-preview-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'write'

    runs-on: ubuntu-latest
    steps:

      # Checkout

      - name: Checkout Repository
        uses: actions/checkout@v4

      # Get PR branch name

      - name: Parse current branch name
        id: parse-branch-name
        # run: echo "branch=$(echo ${{ github.head_ref }} | sed 's/\//-/g' | tr -d '[:space:]')" >> $GITHUB_OUTPUT
        run: |
          echo ${{ github.ref_name }}
          echo "------------------------------------------------------------------------"
          echo ${{ toJson(github) }}
          echo "branch_name=$(echo ${{ github.ref_name }} | sed 's/\//-/g' | tr -d '[:space:]')" >> $GITHUB_OUTPUT

      # GCP setup
        
      - name: Authenticate to GCP
        id: gcp-auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GAR_CREDENTIALS_JSON }}

      - name: Install google cloud sdk
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '456.0.0'

      # Get docker image name and image path

      - name: Get docker preview image name
        id: get-docker-image
        run: echo "image_path=${{ env.LOCATION }}/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ steps.parse-branch-name.outputs.branch_name }}-${{ github.run_attempt }}" >> $GITHUB_OUTPUT

      - name: Log Preview Docker image path
        run: echo ${{ steps.get-docker-image.outputs.image_path }}
