name: Build and Deploy PR Preview to Cloud Run

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:

      # Checkout

      - name: Checkout Repository
        uses: actions/checkout@v4

      # Get PR branch name and latest short commit hash

      - name: Parse current branch name
        id: parse-branch-name
        run: echo "branch=$(echo ${{ github.head_ref }} | sed 's/\//-/g' | tr -d '[:space:]')" >> $GITHUB_OUTPUT

      - name: Parse commit hash
        id: parse-commit-hash
        run: echo "commit_sha=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})" >> $GITHUB_OUTPUT

      - name: Log branch name and commit sha
        run: |
          echo ${{ steps.parse-branch-name.outputs.branch }}
          echo ${{ steps.parse-commit-hash.outputs.commit_sha }}
