name: Build and Deploy PR Preview to Cloud Run

on:
  pull_request:
    branches:
      - main

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  GAR_JSON_KEY: ${{ secrets.GAR_JSON_KEY }}
  SERVICE: preview-demo
  IMAGE: preview-demo-pr

jobs:
  build-publish-deploy-preview:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:

      # 1. Checkout

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Latest Commit Head
        id: commit-sha
        run: echo "commit_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # 2. Authenticate to GCP
        
      - name: Authenticate to GCP
        id: gcp-auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GAR_JSON_KEY }}

      # 3. Authenticate Docker to Google Cloud Artifact Registry (GAR)

      - name: Login to Google Artifact Registry (GAR)
        id: docker-gar-auth
        run: |
          cat ${{ steps.gcp-auth.outputs.credentials_file_path }} | docker login -u _json_key --password-stdin ${{ env.GAR_LOCATION }}-docker.pkg.dev

      # Setup new docker image preview tag with publish path

      - name: Generate Docker preview image path
        id: docker-publish-path
        run: |
          echo "image_path=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE }}/${{ env.IMAGE }}-${{ steps.commit-sha.outputs.commit_sha }}:${{ github.run_number }}" >> $GITHUB_OUTPUT

      # 4. Build Docker Preview Image and Publish to GAR

      - name: Build and Push Preview Image to GAR
        id: build-and-publish
        run: |
          docker build -t ${{ steps.docker-publish-path.outputs.image_path }} ./
          docker push ${{ steps.docker-publish-path.outputs.image_path }}

      # 5. Deploy the Image with Cloud Run

      - name: Deploy Preview to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: preview-demo-pr
          region: ${{ env.GAR_LOCATION }}
          image: ${{ steps.docker-publish-path.outputs.image_path }}
          port: 80

      # 6. Log the Cloud Run url output

      - name: Preview URL
        run: echo ${{ steps.deploy.outputs.url }}
