name: Preview - Build and Deploy PR Preview to Cloud Run

on:
  workflow_dispatch

env:
  REGION: ${{ secrets.GAR_REGION }}
  LOCATION: ${{ secrets.GAR_LOCATION }}
  PROJECT_ID: ${{ secrets.GAR_PROJECT_ID }}
  REPO: ${{ secrets.GAR_REPO }}
  GAR_CREDENTIALS_JSON: ${{ secrets.GAR_JSON_KEY }}
  IMAGE: ${{ secrets.GAR_IMAGE }}
  SERVICE: ${{ secrets.CLOUDRUN_SERVICE }}

jobs:
  build-preview-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'write'

    runs-on: ubuntu-latest
    steps:

      # Checkout

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install YQ/JQ
        run: |
          YQ=4.16.1
          curl -sL https://github.com/mikefarah/yq/releases/download/v${YQ}/yq_linux_amd64 -o /usr/local/bin/yq && chmod +x /usr/local/bin/yq
          curl -sL https://stedolan.github.io/jq/download/linux64/jq -o /usr/local/bin/jq && chmod +x /usr/local/bin/jq

      # Get PR branch name

      - name: Parse current branch name
        id: parse-branch-name
        run: |
          echo "branch_name=$(echo ${{ github.ref_name }} | sed 's|^[^/]*/[^/]*/*||' | sed 's/\//-/g' | tr -d '[:space:]')" >> $GITHUB_OUTPUT
          echo "commit_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

      # GCP setup
        
      - name: Authenticate to GCP
        id: gcp-auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GAR_CREDENTIALS_JSON }}

      - name: Install google cloud sdk
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '456.0.0'

      # Get docker image name and image path

      - name: Get docker preview image name
        id: get-docker-image
        run: echo "image_tag=${{ env.LOCATION }}/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ steps.parse-branch-name.outputs.branch_name }}-${{ steps.parse-branch-name.outputs.commit_sha }}" >> $GITHUB_OUTPUT

      # Configure, Build Docker Preview Image and Publish to GAR

      - name: Build and Push Preview Image to GAR
        id: build-and-publish
        run: |
          gcloud auth configure-docker ${{ env.LOCATION }}
          docker build -t ${{ steps.get-docker-image.outputs.image_tag }} ./
          docker push ${{ steps.get-docker-image.outputs.image_tag }}

      # Deploy the Image with Cloud Run

      - name: Deploy to Cloud Run
        id: deploy
        run: |
          OUTPUT=gcloud-deploy-output.log
          gcloud run deploy ${{ env.SERVICE }}-${{ steps.parse-branch-name.outputs.branch_name }} --image ${{ steps.get-docker-image.outputs.image_tag }} --region ${{ env.REGION }} --allow-unauthenticated --update-labels managed-by=github-actions --format="flattened(status.url, status.traffic[0].url)" > $OUTPUT
          cat $OUTPUT
          echo "DEPLOYMENT_URL=$(yq eval '.url' $OUTPUT)" >> $GITHUB_OUTPUT

      - name: Log Preview URL
        run: |
          Changes are deployed, you can preview it on ${{ steps.deploy.outputs.DEPLOYMENT_URL }}
