name: Preview - Build and Deploy PR Preview to Cloud Run

on:
  workflow_dispatch:

permissions: write-all

jobs:
  build-preview-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'write'

    runs-on: ubuntu-latest
    steps:

      # Checkout

      - name: Checkout Repository
        uses: actions/checkout@v4

      # Get PR branch name

      - name: Parse current branch name
        id: parse-branch-name
        # run: echo "branch=$(echo ${{ github.head_ref }} | sed 's/\//-/g' | tr -d '[:space:]')" >> $GITHUB_OUTPUT
        run: echo ${{ toJson(github) }}

      # - name: Log branch name
      #   run: |
      #     echo ${{ steps.parse-branch-name.outputs.branch }}
