# Clean up long opened PRs' images and cloud run services
name: Clean up open PRs

on:
  workflow_dispatch:
    inputs:
      force_cleanup:
        description: 'Force cleanup of preview environments'
        required: false
        default: 'false'

env:
  REGION: asia-south1
  LOCATION: asia-south1-docker.pkg.dev
  IMAGE_PATH: asia-south1-docker.pkg.dev/cloud-run-preview-demo/cloud-run-repo/preview
  SERVICE: preview

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set the multiline value in bash
        id: step_one
        run: |
          {
            echo 'JSON_RESPONSE<<EOF'
            curl https://example.com
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Log multiline value
        run: |
          echo "$JSON_RESPONSE"

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GAR_JSON_KEY }}

      - name: Install google cloud sdk
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '456.0.0'

      - name: Find Open PRs with Preview Label
        id: extract-open-prs
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            const prLastUpdatedLimit = 1 * 60 * 1000; // 1 minute for testing purposes
            const devOpenPRBranches = pullRequests.filter(pr => {
              const lastUpdatedAt = +(new Date(pr.updated_at));
              return pr.base.ref === 'main' && Date.now() - lastUpdatedAt > prLastUpdatedLimit;
            }).map(pr => (pr.head.ref.split('/').slice(2)[0] || pr.head.ref || "").toLowerCase());
            return devOpenPRBranches;

      - name: Parse inactive branches
        run: |
          echo "$INACTIVE_BRANCHES"
          # parsed_branches=$(jq '.[]' <<< "$INACTIVE_BRANCHES")
          # echo "$parsed_branches"
          echo "BRANCHES=$INACTIVE_BRANCHES" >> $GITHUB_ENV
        env:
          INACTIVE_BRANCHES: ${{ steps.extract-open-prs.outputs.result }}

      - name: Delete cloud run services of long opened PR branches
        run: |
          echo "$BRANCHES"
          for branch in $(jq '.[]' <<< "$INACTIVE_BRANCHES"); do
            SERVICE=$(gcloud run services list --region $REGION --format="value(metadata.name)" --filter="metadata.name ~ $branch")
            echo "Service for $branch is $SERVICE"
            if [ ! -z $SERVICE ]; then
              gcloud run services delete $SERVICE --region $REGION --quiet
            else
              echo "cloud run service $SERVICE for $branch not found"
            fi
          done

      - name: Delete preview docker images
        run: |
          for branch in $(jq '.[]' <<< "$INACTIVE_BRANCHES"); do
            TAGS=$(gcloud artifacts docker tags list $IMAGE_PATH --format="value(tag)" --filter="tag ~ $branch")
            echo "tags for $branch are $TAGS"
            for tag in $TAGS; do
              gcloud artifacts docker images delete $IMAGE_PATH:$tag --quiet
            done
          done
