name: Get new release and publish to dev

on:
  push:
    branches:
    - dev

jobs:
  get-next-release:
    name: get next release version
    uses: ./.github/workflows/call_get-next-release.yaml
    secrets: inherit
    
  publish-to-dev:
    name: Publish to dev
    needs: get-next-release
    uses: ./.github/workflows/call_publish-to-dev.yaml
    secrets: inherit
    with:
      release-version: ${{ needs.get-next-release.outputs.release-version }}
