name: Get new release and publish to dev

on:
  push:
    branches:
    - dev

env:
  REGION: asia-south1
  LOCATION: asia-south1-docker.pkg.dev
  IMAGE: asia-south1-docker.pkg.dev/cloud-run-preview-demo/cloud-run-repo/release
  SERVICE: release
  NEXT_RELEASE: ""

jobs:
  get-next-release:
    name: get next release version
    uses: ./.github/workflows/call_get-next-release.yaml
    secrets: inherit
