name: Get new release and publish to dev

on:
  push:
    branches:
    - dev

jobs:
  get-next-release:
    name: get next release version
    uses: ./.github/workflows/call_get-next-release.yaml
    secrets: inherit
    with:
      branch: dev
