# Release - Build and publish release image and Deploy to Cloud Run.
name: Release to dev

on:
  push:
    branches:
    - dev

env:
  REGION: asia-south1
  LOCATION: asia-south1-docker.pkg.dev
  IMAGE: asia-south1-docker.pkg.dev/cloud-run-preview-demo/cloud-run-repo/release
  SERVICE: release

jobs:
  build-publish-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Use Node.js 21.2
      uses: actions/setup-node@v3
      with:
        node-version: '21.2'

    - name: Log github context
      run: echo $JSON
      env:
        JSON: ${{ toJSON(github) }}

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: Dry run Semantic release to get next version
      run: GH_TOKEN=${{secrets.GITHUB_TOKEN}} yarn semantic-release

    - name: Extract next release tag
      run: GH_TOKEN=${{secrets.GITHUB_TOKEN}} yarn semantic-release --dry-run --verbose | grep -oP 'Skip \\K.* tag creation in dry-run mode' | cut -d ' ' -f 1 || echo 'NotFound'
