name: Pull Request - Build, Publish and deploy to Cloud Run when a pull request is raised against main branch

on:
  pull_request:
    branches:
      - main2
    types: [opened, synchronize, reopened]

env:
  REGION: asia-south1
  LOCATION: asia-south1-docker.pkg.dev
  IMAGE_PATH: asia-south1-docker.pkg.dev/cloud-run-preview-demo/cloud-run-repo/preview
  SERVICE: preview

jobs:
  build-preview-deploy:
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log github context
      run: echo $JSON
      env:
        JSON: ${{ toJSON(github) }}

    # - name: Install YQ/JQ
    #   run: |
    #     YQ=4.16.1
    #     curl -sL https://github.com/mikefarah/yq/releases/download/v${YQ}/yq_linux_amd64 -o /usr/local/bin/yq && chmod +x /usr/local/bin/yq

    # - name: Authenticate to GCP
    #   id: gcp-auth
    #   uses: google-github-actions/auth@v2
    #   with:
    #     credentials_json: ${{ secrets.GAR_JSON_KEY }}

    # - name: Install google cloud sdk
    #   uses: 'google-github-actions/setup-gcloud@v2'
    #   with:
    #     version: '456.0.0'

    # - name: Parse current branch name
    #   id: parse-branch-name
    #   run: |
    #     echo "branch_name=$(echo ${{ github.head_ref }} | sed 's|^[^/]*/[^/]*/*||' | sed 's/\//-/g' | sed 's/.*/\L&/g' | tr -d '[:space:]')" >> $GITHUB_OUTPUT
    #     echo "commit_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

    # - name: Get docker preview image name
    #   id: get-docker-image
    #   run: echo "image_tag=${{ env.IMAGE_PATH }}:${{ steps.parse-branch-name.outputs.branch_name }}-${{ steps.parse-branch-name.outputs.commit_sha }}" >> $GITHUB_OUTPUT

    # - name: Build and Push Preview Image to GAR
    #   id: build-and-publish
    #   run: |
    #     gcloud auth configure-docker ${{ env.LOCATION }}
    #     docker build -t ${{ steps.get-docker-image.outputs.image_tag }} ./
    #     docker push ${{ steps.get-docker-image.outputs.image_tag }}

    # - name: Deploy to Cloud Run
    #   id: deploy
    #   run: |
    #     OUTPUT=gcloud-deploy-output.log
    #     gcloud run deploy ${{ env.SERVICE }}-${{ steps.parse-branch-name.outputs.branch_name }} --image ${{ steps.get-docker-image.outputs.image_tag }} --region ${{ env.REGION }} --allow-unauthenticated --update-labels managed-by=github-actions --format="flattened(status.url, status.traffic[0].url)" > $OUTPUT
    #     cat $OUTPUT
    #     echo "DEPLOYMENT_URL=$(yq eval '.url' $OUTPUT)" >> $GITHUB_OUTPUT

    # - name: Comment Deployed URL
    #   uses: mshick/add-pr-comment@v2
    #   with:
    #     message: Changes are deployed to preview environment - ${{ steps.deploy.outputs.DEPLOYMENT_URL }}
