name: Get new release and publish to dev

on:
  push:
    branches:
    - dev

jobs:
  get-next-release:
    name: get next release version
    uses: ./.github/workflows/call_get-next-release.yaml
    secrets: inherit

  log-next-release:
    name: Log next release version
    runs-on: ubunut-latest
    needs: get-next-release
    steps:
      - name: Log release
        run: echo ${{ needs.get-next-release.outputs.release-version }}

  test-conditional-job:
    name: test conditional job
    runs-on: ubuntu-latest
    needs: [get-next-release, log-next-release]
    if: ${{ needs.get-next-release.outputs.release-version }} != ''
    steps:
      - run: echo "test-conditional-job - Next release version is ${{ needs.get-next-release.outputs.release-version }}"

  test-conditional-job2:
    name: test conditional job2
    runs-on: ubuntu-latest
    needs: [get-next-release, log-next-release]
    if: ${{ needs.get-next-release.outputs.release-version != '' }}
    steps:
      - run: echo "test-conditional-job2 - Next release version is ${{ needs.get-next-release.outputs.release-version }}"

  publish-to-dev:
    name: Publish to dev
    needs: [get-next-release, log-next-release]
    uses: ./.github/workflows/call_publish-release-notes.yaml
    secrets: inherit
